name: Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Using pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm i

      - name: Running Build
        run: pnpm run build

      - name: Running Storybook Build
        run: pnpm run build:storybook
