name: Updating Dependencies

on:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the head commit of the branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - run: pnpm install

      - name: Setup
        uses: actions/setup-go@v2

      - name: Run auto dependency update
        uses: romoh/dependencies-autoupdate@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          update-command: "'pnpm run template:update:dependencies && pnpm i && pnpm run lint && pnpm t'"
