name: Updating Packages

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: package-update
        uses: taichi/actions-package-update@master
        env:
          AUTHOR_EMAIL: ccctux@gmail.com
          AUTHOR_NAME: Viacheslav Miroshko
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: -u --target minor
